title: manu.ninja
description: manu.ninja is the personal blog of Manuel Wieser, where he talks about front-end development, web development, coding, games and digital art
url: "http://manu.ninja"
email: office@manuelwieser.com

markdown: kramdown
highlighter: false

sass:
  style: compressed

permalink: /:title
gems: [jekyll-sitemap]
