title: manu.ninja
description: Front-End Development, Games and Digital Art
url: "http://manu.ninja"
email: office@manuelwieser.com

markdown: kramdown
highlighter: false

sass:
  style: compressed

permalink: /:title.html
gems:
  - jekyll-sitemap
  - jekyll-minifier
