title: manu.ninja
description: Front-End Development, Games and Digital Art
url: "http://manu.ninja"
email: office@manuelwieser.com

markdown: kramdown
highlighter: false

permalink: /:categories/:title
gems: [jekyll-sitemap]
