title: manu.ninja
email: office@manuelwieser.com
description: Front-End Development, Games and Digital Art
permalink: /:categories/:title
url: "http://manu.ninja"
markdown: redcarpet
highlighter: false
